FROM photon:4.0

ENV PGDATA /var/lib/postgresql/data

RUN tdnf install -y shadow gzip postgresql13 findutils bc >> /dev/null \
    && tdnf clean all

RUN tdnf erase -y toybox && tdnf install -y util-linux net-tools