swagger: '2.0'
info:
  title: Harbor API
  description: These APIs provide services for manipulating Harbor project.
  version: ''
host: localhost
schemes:
  - http
  - https
basePath: /api/
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  basic:
    type: basic
security:
  - basic: []
  - {}
paths:
  /version:
    get:
      summary: Get API version
      description: Get the version of API that supported by the Harbor instance.
      tags:
        - Version
      responses:
        '200':
          description: The supported API version
          schema:
            type: object
            properties:
              version:
                type: string