swagger: '2.0'
info:
  title: Harbor API
  description: These APIs provide services for manipulating Harbor project.
  version: '2.0'
host: localhost
schemes:
  - http
  - https
basePath: /api/v2.0
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  basic:
    type: basic
security:
  - basic: []
  - {}
paths:
  /health:
    get:
      summary: Check the status of Harbor components
      description: Check the status of Harbor components. This path does not require authentication.
      tags:
        - health
      operationId: getHealth
      parameters:
        - $ref: '#/parameters/requestId'
      responses:
        '200':
          description: The health status of Harbor components
          schema:
            $ref: '#/definitions/OverallHealthStatus'
        '500':
          $ref: '#/responses/500'